all:
	g++ -g -O3 -std=c++11 CodecData.cpp main.cpp OpenGLException.cpp Egl.cpp Matrix4.cpp Scene.cpp EglException.cpp NV12Shader.cpp Vector3.cpp Exception.cpp OpenGL.cpp X11Window.cpp -o XU4VideoCube -L/usr/lib/arm-linux-gnueabihf/mali-egl/ -lmali -lX11 -lpthread

